In [1]:
from phasesim import *

/home/dsuo/miniconda3/lib/python3.6/site-packages/matplotlib/__init__.py:886: MatplotlibDeprecationWarning:
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))

In [2]:
parse_heartbeats("data/test.txt")

,instructions,cycles,heartbeat_ipc,cumulative_ipc,hours,minutes,seconds
0,1000000,533601,1.874060,1.874060,0,0,4
1,2000000,1046321,1.950380,1.911460,0,0,7
2,3000003,1584709,1.857400,1.893090,0,0,10
3,4000001,2098715,1.945500,1.905930,0,0,14
4,5000000,2675092,1.734970,1.869090,0,0,16
5,6000000,3222376,1.827200,1.861980,0,0,19
6,7000001,3735121,1.950290,1.874100,0,0,22
7,8000003,4273433,1.857660,1.872030,0,0,25
8,9000001,4781503,1.968230,1.882250,0,0,29
9,10000003,5310698,1.889670,1.882990,0,0,32
10,11000000,6755854,0.691965,0.691965,0,0,37
11,12000000,8211075,0.687181,0.689564,0,0,42
12,13000001,9653700,0.693182,0.690766,0,0,47
13,14000000,11106293,0.688423,0.690179,0,0,53
14,15000000,12557067,0.689287,0.690000,0,0,58
15,16000000,13865295,0.764393,0.701377,0,1,3
16,17000002,15096237,0.812388,0.715341,0,1,8
17,18000000,16330720,0.810054,0.725951,0,1,13
18,19000003,17564821,0.810309,0.734447,0,1,18
19,20000003,18803866,0.807073,0.741116,0,1,23

In [ ]:
parse_telemetry("data/test.txt", "CPIPhaseDetector", columns)